name = "sf-pixel"
type = "web_pixel_extension"
uid = "91d5697b-61ba-c273-3692-629312971ccdf9214c4a"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.accountID]
name = "Account ID"
description = "Account ID"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
