# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "616431d20b1e35e8672963828655d4b1"
name = "convertkit-convertflow"
application_url = "https://adventurous-mercy-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_themes,write_themes,write_script_tags,read_script_tags,read_inventory,read_analytics,read_content,write_content"

[auth]
redirect_urls = [
  "https://adventurous-mercy-production.up.railway.app/auth/callback",
  "https://adventurous-mercy-production.up.railway.app/auth/shopify/callback",
  "https://adventurous-mercy-production.up.railway.app/api/auth/callback"
]
