import fs from 'fs';
import path from 'path';

const regJson = JSON.parse(fs.readFileSync('app/data/templates/theme-engine/registry.json', 'utf8'));
const allIds = new Set(regJson.components.map((c: any) => c.componentId));

export const HOMEPAGES = [
  // 1. BEWAKOOF / URBAN MONKEY (Cyber Streetwear) - 23 sections
  {
    id: 'streetwear-cyber-home',
    name: 'Bewakoof / Urban Monkey Cyber Streetwear',
    niche: 'clothing',
    family: 'Streetwear',
    archetype: 'cyber-brutalist',
    styleBadge: '🔥 Gen-Z Oversized Drops',
    accentColor: '#ff5500',
    description: 'High-octane Gen-Z streetwear benchmark: limited drop tickers, live stock counters, shoppable reels, street lookbook, VIP rewards, and dark brutalist aesthetics.',
    announcement: 'announcement-neo-brutalist-v1',
    header: 'header-neo-brutalist-v1',
    footer: 'footer-neo-brutalist-v1',
    sections: [
      { componentId: 'hp22-marquee' },
      { componentId: 'hero-neo-brutalist-v1' },
      { componentId: 'hp22-usp' },
      { componentId: 'collection-neo-brutalist-v1' },
      { componentId: 'hp22-category-tiles' },
      { componentId: 'product-neo-brutalist-v1' },
      { componentId: 'hp22-bestsellers' },
      { componentId: 'banner-neo-brutalist-v1' },
      { componentId: 'hp22-offer-banner' },
      { componentId: 'hp22-ugc-reels' },
      { componentId: 'grid-neo-brutalist-v1' },
      { componentId: 'hp22-brand-story' },
      { componentId: 'grid-featured-lookbook-v1' },
      { componentId: 'hp22-instagram' },
      { componentId: 'trust-neo-brutalist-v1' },
      { componentId: 'hp22-press-logos' },
      { componentId: 'hp22-testimonials' },
      { componentId: 'story-neo-brutalist-v1' },
      { componentId: 'hp22-bundle-offer' },
      { componentId: 'hp22-founder-note' },
      { componentId: 'hp22-faq' },
      { componentId: 'newsletter-neo-brutalist-v1' },
      { componentId: 'popup-neo-brutalist-v1' }
    ]
  },
  // 2. SABYASACHI / RAW MANGO (Royal Heritage Couture) - 23 sections
  {
    id: 'ethnic-royal-home',
    name: 'Sabyasachi / Raw Mango Royal Couture',
    niche: 'clothing',
    family: 'Luxury',
    archetype: 'royal-heritage',
    styleBadge: '👑 100% Zari Bridal Heritage',
    accentColor: '#d4af37',
    description: 'Ultra-luxury royal Indian couture benchmark: gold zari announcements, imperial Mughal archway hero, bridal trousseau builder, karigar story, and heirloom styling.',
    announcement: 'announcement-luxury-v1',
    header: 'hp7-header',
    footer: 'footer-luxury-v1',
    sections: [
      { componentId: 'hp7-marquee' },
      { componentId: 'hp7-hero' },
      { componentId: 'hp7-usp' },
      { componentId: 'collection-luxury-v1' },
      { componentId: 'hp7-bestsellers' },
      { componentId: 'product-luxury-v1' },
      { componentId: 'story-materials-showcase-v1' },
      { componentId: 'hp7-offer-banner' },
      { componentId: 'grid-luxury-v1' },
      { componentId: 'story-luxury-v1' },
      { componentId: 'hp7-15-instagram-grid' },
      { componentId: 'trust-luxury-v1' },
      { componentId: 'hp7-testimonials' },
      { componentId: 'hp7-press-logos' },
      { componentId: 'banner-luxury-v1' },
      { componentId: 'gallery-luxury-v1' },
      { componentId: 'hp7-faq' },
      { componentId: 'newsletter-luxury-v1' },
      { componentId: 'trust-before-after-luxury-v1' },
      { componentId: 'popup-luxury-v1' },
      { componentId: 'collection-luxury-v2' },
      { componentId: 'product-luxury-v2' },
      { componentId: 'banner-luxury-v2' }
    ]
  },
  // 3. SNITCH / DAMENSCH (Minimal Everyday Menswear) - 23 sections
  {
    id: 'apparel-minimal-home',
    name: 'Snitch / Damensch Minimal Everyday Menswear',
    niche: 'clothing',
    family: 'Minimal',
    archetype: 'nordic-clean',
    styleBadge: '🌿 4-Way Stretch Tech-Cotton',
    accentColor: '#2d4a3e',
    description: 'Modern men’s apparel benchmark: 360 stretch fabric matrix, capsule wardrobe builder, anti-odor specs, clean grid, and high-conversion 1-click cart triggers.',
    announcement: 'announcement-minimal-v1',
    header: 'hp10-header',
    footer: 'footer-minimal-v1',
    sections: [
      { componentId: 'hp10-marquee' },
      { componentId: 'hp10-hero' },
      { componentId: 'hp10-usp' },
      { componentId: 'collection-minimal-v1' },
      { componentId: 'hp10-bestsellers' },
      { componentId: 'product-minimal-v1' },
      { componentId: 'hp10-image-with-text' },
      { componentId: 'story-minimal-v1' },
      { componentId: 'hp10-comparison-table' },
      { componentId: 'grid-minimal-v1' },
      { componentId: 'hp10-instagram' },
      { componentId: 'trust-minimal-v1' },
      { componentId: 'hp10-testimonials' },
      { componentId: 'hp10-press-logos' },
      { componentId: 'banner-minimal-v1' },
      { componentId: 'gallery-minimal-v1' },
      { componentId: 'hp10-faq' },
      { componentId: 'newsletter-minimal-v1' },
      { componentId: 'popup-minimal-v1' },
      { componentId: 'collection-minimal-v2' },
      { componentId: 'product-minimal-v2' },
      { componentId: 'story-minimal-v2' },
      { componentId: 'banner-minimal-v2' }
    ]
  },
  // 4. MAMAEARTH / FOREST ESSENTIALS (Clean Ayurveda & Botanicals) - 23 sections
  {
    id: 'beauty-organic-home',
    name: 'Mamaearth / Forest Essentials Clean Ayurveda',
    niche: 'beauty',
    family: 'Organic',
    archetype: 'botanical-glow',
    styleBadge: '🍃 Cold-Pressed Botanical Glow',
    accentColor: '#2e5a44',
    description: 'Clean Ayurvedic beauty benchmark: ingredient sourcing map, dermatologist certifications, toxic-free 10-free guarantee, and before/after clinical results.',
    announcement: 'announcement-warm-v1',
    header: 'header-warm-v1',
    footer: 'footer-warm-v1',
    sections: [
      { componentId: 'hp1-marquee' },
      { componentId: 'hp1-hero' },
      { componentId: 'hp1-usp' },
      { componentId: 'collection-warm-v1' },
      { componentId: 'hp1-bestsellers' },
      { componentId: 'product-warm-v1' },
      { componentId: 'story-warm-v1' },
      { componentId: 'hp1-grid' },
      { componentId: 'banner-warm-v1' },
      { componentId: 'hp1-instagram' },
      { componentId: 'trust-warm-v1' },
      { componentId: 'hp1-testimonials' },
      { componentId: 'hp1-press-logos' },
      { componentId: 'gallery-warm-v1' },
      { componentId: 'hp1-faq' },
      { componentId: 'newsletter-warm-v1' },
      { componentId: 'popup-warm-v1' },
      { componentId: 'collection-warm-v2' },
      { componentId: 'product-warm-v2' },
      { componentId: 'story-warm-v2' },
      { componentId: 'banner-warm-v2' },
      { componentId: 'trust-warm-v2' },
      { componentId: 'gallery-warm-v2' }
    ]
  },
  // 5. MINIMALIST / THE DERMA CO (Clinical Derma Lab) - 23 sections
  {
    id: 'beauty-clinical-home',
    name: 'Minimalist / The Derma Co Clinical Actives',
    niche: 'beauty',
    family: 'Clinical',
    archetype: 'derma-lab',
    styleBadge: '🔬 10% Niacinamide + 2% Salicylic',
    accentColor: '#0284c7',
    description: 'High-efficacy clinical derma benchmark: active percentage matrix, lab trial statistics, skin barrier repair guide, pH balance charts, and chemist formulation specs.',
    announcement: 'announcement-clean-v1',
    header: 'header-clean-v1',
    footer: 'hp14-footer',
    sections: [
      { componentId: 'hp14-marquee' },
      { componentId: 'hp14-hero' },
      { componentId: 'hp14-usp' },
      { componentId: 'collection-clean-v1' },
      { componentId: 'hp14-bestsellers' },
      { componentId: 'product-clean-v1' },
      { componentId: 'hp14-image-with-text' },
      { componentId: 'story-clean-v1' },
      { componentId: 'banner-clean-v1' },
      { componentId: 'grid-clean-v1' },
      { componentId: 'trust-clean-v1' },
      { componentId: 'gallery-clean-v1' },
      { componentId: 'hp14-faq' },
      { componentId: 'hp14-newsletter' },
      { componentId: 'popup-clean-v1' },
      { componentId: 'collection-clean-v2' },
      { componentId: 'product-clean-v2' },
      { componentId: 'story-clean-v2' },
      { componentId: 'banner-clean-v2' },
      { componentId: 'trust-clean-v2' },
      { componentId: 'grid-clean-v2' },
      { componentId: 'gallery-clean-v2' },
      { componentId: 'newsletter-clean-v1' }
    ]
  },
  // 6. SUGAR / KAY BEAUTY (Velvet Glam & Makeup) - 23 sections
  {
    id: 'beauty-glamour-home',
    name: 'Sugar Cosmetics / Kay Beauty Velvet Glam',
    niche: 'beauty',
    family: 'Glamour',
    archetype: 'glamour-studio',
    styleBadge: '💎 24HR Waterproof Transferproof',
    accentColor: '#e879f9',
    description: 'High-glamour makeup & haute perfumery benchmark: skin tone shade matrix, 24hr wear stress-test, celebrity lookbook, red-carpet reels, and combo creator.',
    announcement: 'announcement-editorial-v1',
    header: 'header-editorial-v1',
    footer: 'footer-editorial-v1',
    sections: [
      { componentId: 'hp19-marquee' },
      { componentId: 'hp19-hero' },
      { componentId: 'hp19-usp' },
      { componentId: 'collection-editorial-v1' },
      { componentId: 'hp19-bestsellers' },
      { componentId: 'product-editorial-v1' },
      { componentId: 'hp19-image-with-text' },
      { componentId: 'hp19-grid' },
      { componentId: 'banner-editorial-v1' },
      { componentId: 'hp19-instagram' },
      { componentId: 'trust-editorial-v1' },
      { componentId: 'hp19-testimonials' },
      { componentId: 'story-editorial-v1' },
      { componentId: 'gallery-editorial-v1' },
      { componentId: 'hp19-faq' },
      { componentId: 'newsletter-editorial-v1' },
      { componentId: 'popup-editorial-v1' },
      { componentId: 'collection-editorial-v2' },
      { componentId: 'product-editorial-v2' },
      { componentId: 'story-editorial-v2' },
      { componentId: 'banner-editorial-v2' },
      { componentId: 'trust-editorial-v2' },
      { componentId: 'gallery-editorial-v2' }
    ]
  },
  // 7. TANISHQ / AMRAPALI (Royal Polki & Fine Gold) - 23 sections
  {
    id: 'jewellery-heritage-home',
    name: 'Tanishq / Amrapali Royal Polki & Gold',
    niche: 'jewellery',
    family: 'Heritage Jewellery',
    archetype: 'royal-polki',
    styleBadge: '👑 BIS 916 Hallmarked Gold',
    accentColor: '#eab308',
    description: 'Imperial Indian fine jewellery benchmark: BIS 916 hallmark laser verifier, uncut Polki setting zoom, bridal necklace layered stack builder, and museum styling.',
    announcement: 'announcement-luxury-v2',
    header: 'header-luxury-v2',
    footer: 'hp8-footer',
    sections: [
      { componentId: 'hp8-marquee' },
      { componentId: 'hp8-hero' },
      { componentId: 'hp8-usp' },
      { componentId: 'collection-luxury-v2' },
      { componentId: 'hp8-bestsellers' },
      { componentId: 'product-luxury-v2' },
      { componentId: 'hp8-grid' },
      { componentId: 'story-luxury-v2' },
      { componentId: 'banner-luxury-v2' },
      { componentId: 'hp8-instagram' },
      { componentId: 'trust-luxury-v2' },
      { componentId: 'hp8-testimonials' },
      { componentId: 'hp8-press-logos' },
      { componentId: 'gallery-luxury-v2' },
      { componentId: 'hp8-faq' },
      { componentId: 'newsletter-luxury-v2' },
      { componentId: 'popup-luxury-v2' },
      { componentId: 'collection-luxury-v3' },
      { componentId: 'product-luxury-v3' },
      { componentId: 'story-luxury-v3' },
      { componentId: 'banner-luxury-v3' },
      { componentId: 'trust-luxury-v3' },
      { componentId: 'gallery-luxury-v3' }
    ]
  },
  // 8. CARATLANE / BLUESTONE (Modern Solitaire Diamonds) - 23 sections
  {
    id: 'jewellery-diamond-home',
    name: 'CaratLane / BlueStone Modern Solitaire Diamond',
    niche: 'jewellery',
    family: 'Modern Fine Jewellery',
    archetype: 'modern-solitaire',
    styleBadge: '💎 IGI & GIA Certified 4Cs',
    accentColor: '#0ea5e9',
    description: 'Modern solitaire & lab diamond benchmark: 4Cs interactive clarity scale, platinum alloy durability test, engagement ring customizer, and 360 sparkle visualizer.',
    announcement: 'announcement-clean-v2',
    header: 'header-clean-v2',
    footer: 'footer-clean-v2',
    sections: [
      { componentId: 'hero-clean-v1' },
      { componentId: 'collection-clean-v1' },
      { componentId: 'product-clean-v1' },
      { componentId: 'grid-clean-v1' },
      { componentId: 'banner-clean-v1' },
      { componentId: 'story-clean-v1' },
      { componentId: 'trust-clean-v1' },
      { componentId: 'gallery-clean-v1' },
      { componentId: 'newsletter-clean-v1' },
      { componentId: 'popup-clean-v1' },
      { componentId: 'hero-clean-v2' },
      { componentId: 'collection-clean-v2' },
      { componentId: 'product-clean-v2' },
      { componentId: 'grid-clean-v2' },
      { componentId: 'banner-clean-v2' },
      { componentId: 'story-clean-v2' },
      { componentId: 'trust-clean-v2' },
      { componentId: 'gallery-clean-v2' },
      { componentId: 'hero-clean-v3' },
      { componentId: 'collection-clean-v3' },
      { componentId: 'product-clean-v3' },
      { componentId: 'grid-clean-v3' },
      { componentId: 'banner-clean-v3' }
    ]
  },
  // 9. GIVA / SHAYA (Handcrafted 925 Silver) - 23 sections
  {
    id: 'jewellery-silver-home',
    name: 'GIVA / Shaya Handcrafted 925 Silver',
    niche: 'jewellery',
    family: 'Artisan Silver',
    archetype: 'artisan-silver',
    styleBadge: '🥈 925 Solid Anti-Tarnish Rhodium',
    accentColor: '#78716c',
    description: 'Everyday silver jewellery benchmark: anti-tarnish rhodium seal demo, 3-ring layering trio builder, luxury unboxing gift packaging, and daily wear styling guide.',
    announcement: 'announcement-retro-v1',
    header: 'header-retro-v1',
    footer: 'footer-retro-v1',
    sections: [
      { componentId: 'hero-retro-v1' },
      { componentId: 'collection-retro-v1' },
      { componentId: 'product-retro-v1' },
      { componentId: 'grid-retro-v1' },
      { componentId: 'banner-retro-v1' },
      { componentId: 'story-retro-v1' },
      { componentId: 'trust-retro-v1' },
      { componentId: 'gallery-retro-v1' },
      { componentId: 'newsletter-retro-v1' },
      { componentId: 'popup-retro-v1' },
      { componentId: 'hero-retro-v2' },
      { componentId: 'collection-retro-v2' },
      { componentId: 'product-retro-v2' },
      { componentId: 'grid-retro-v2' },
      { componentId: 'banner-retro-v2' },
      { componentId: 'story-retro-v2' },
      { componentId: 'trust-retro-v2' },
      { componentId: 'gallery-retro-v2' },
      { componentId: 'hero-retro-v3' },
      { componentId: 'collection-retro-v3' },
      { componentId: 'product-retro-v3' },
      { componentId: 'grid-retro-v3' },
      { componentId: 'banner-retro-v3' }
    ]
  },
  // 10. BOAT / NOISE (Cyber Dark Audio & Wearables) - 23 sections
  {
    id: 'tech-audio-home',
    name: 'boAt / Noise Cyber Dark Audio & Electronics',
    niche: 'tech',
    family: 'Cyber Audio',
    archetype: 'cyber-audio',
    styleBadge: '⚡ 60H Playback · 40ms Low Latency',
    accentColor: '#22c55e',
    description: 'High-energy audio & tech wearables benchmark: bass acoustic waveform, 60-hour battery stress graph, IPX7 waterproof splash test, and BEAST low-latency gaming mode switch.',
    announcement: 'announcement-bold-v1',
    header: 'header-bold-v1',
    footer: 'footer-bold-v1',
    sections: [
      { componentId: 'hero-bold-v1' },
      { componentId: 'collection-bold-v1' },
      { componentId: 'product-bold-v1' },
      { componentId: 'grid-bold-v1' },
      { componentId: 'banner-bold-v1' },
      { componentId: 'story-bold-v1' },
      { componentId: 'trust-bold-v1' },
      { componentId: 'gallery-bold-v1' },
      { componentId: 'newsletter-bold-v1' },
      { componentId: 'popup-bold-v1' },
      { componentId: 'hero-bold-v2' },
      { componentId: 'collection-bold-v2' },
      { componentId: 'product-bold-v2' },
      { componentId: 'grid-bold-v2' },
      { componentId: 'banner-bold-v2' },
      { componentId: 'story-bold-v2' },
      { componentId: 'trust-bold-v2' },
      { componentId: 'gallery-bold-v2' },
      { componentId: 'hero-bold-v3' },
      { componentId: 'collection-bold-v3' },
      { componentId: 'product-bold-v3' },
      { componentId: 'grid-bold-v3' },
      { componentId: 'banner-bold-v3' }
    ]
  }
];

let allPassed = true;
for (const hp of HOMEPAGES) {
  console.log(`Checking ${hp.name} -> ${hp.sections.length} sections`);
  if (!allIds.has(hp.announcement)) { console.error(`  MISSING ANNOUNCEMENT: ${hp.announcement}`); allPassed = false; }
  if (!allIds.has(hp.header)) { console.error(`  MISSING HEADER: ${hp.header}`); allPassed = false; }
  if (!allIds.has(hp.footer)) { console.error(`  MISSING FOOTER: ${hp.footer}`); allPassed = false; }
  for (const s of hp.sections) {
    if (!allIds.has(s.componentId)) { console.error(`  MISSING SECTION: ${s.componentId}`); allPassed = false; }
  }
}

if (allPassed) {
  console.log('🎉 100% SUCCESS! ALL 10 HOMEPAGES (23 SECTIONS EACH = 230 SECTIONS) ARE FULLY RESOLVED IN REGISTRY!');
}
