import fs from 'fs';
import path from 'path';

const regJson = JSON.parse(fs.readFileSync('app/data/templates/theme-engine/registry.json', 'utf8'));
const regMap = new Set(regJson.components.map((c: any) => c.componentId));

export const PAGE_COMPOSITIONS_EXPANDED = [
  {
    id: 'streetwear-cyber-home',
    name: 'Bewakoof / Urban Monkey Cyber Streetwear',
    niche: 'clothing',
    family: 'Streetwear',
    archetype: 'cyber-brutalist',
    styleBadge: '🔥 Gen-Z Oversized Drops',
    accentColor: '#ff5500',
    description: 'High-octane Gen-Z streetwear benchmark: limited drop tickers, live stock counters, shoppable reels, street lookbook, VIP rewards, and dark brutalist aesthetics.',
    announcement: 'announcement-bold-v1',
    header: 'header-bold-v1',
    footer: 'footer-bold-v1',
    sections: [
      'hp22-marquee',
      'hero-bold-v1',
      'hp22-usp',
      'hp22-category-tiles',
      'hp22-bestsellers',
      'banner-countdown-bold-v1',
      'hp22-offer-banner',
      'hp22-ugc-reels',
      'hp22-brand-story',
      'grid-featured-lookbook-v1',
      'hp22-instagram',
      'trust-certifications-v1',
      'hp22-press-logos',
      'hp22-testimonials',
      'hp22-bundle-offer',
      'hp22-founder-note',
      'hp22-faq',
      'hp22-newsletter',
      'hp20-18-footer-promo',
      'popup-spin-wheel-v1',
      'hp22-custom-content',
      'trust-badges-v1',
      'banner-bold-v1'
    ]
  },
  {
    id: 'ethnic-royal-home',
    name: 'Sabyasachi / Raw Mango Royal Couture',
    niche: 'clothing',
    family: 'Luxury',
    archetype: 'royal-heritage',
    styleBadge: '👑 100% Zari Bridal Heritage',
    accentColor: '#d4af37',
    description: 'Ultra-luxury royal Indian couture benchmark: gold zari announcements, imperial Mughal archway hero, bridal trousseau builder, karigar story, and heirloom styling.',
    announcement: 'announcement-luxury-v1',
    header: 'hp7-header',
    footer: 'footer-luxury-mega-v1',
    sections: [
      'hp7-marquee',
      'hp7-hero',
      'hp7-usp',
      'collection-luxury-v1',
      'hp7-bestsellers',
      'story-materials-showcase-v1',
      'hp7-offer-banner',
      'grid-luxury-v1',
      'hp7-15-instagram-grid',
      'trust-before-after-luxury-v1',
      'hp7-testimonials',
      'hp7-press-logos',
      'banner-countdown-luxury-v1',
      'story-founder-note-v1',
      'hp7-faq',
      'newsletter-luxury-v1',
      'hp20-18-footer-promo',
      'popup-exit-intent-luxury-v1',
      'trust-press-quotes-v1',
      'gallery-luxury-v1',
      'story-timeline-v1',
      'trust-certifications-v1'
    ]
  },
  {
    id: 'apparel-minimal-home',
    name: 'Snitch / Damensch Minimal Everyday Menswear',
    niche: 'clothing',
    family: 'Minimal',
    archetype: 'nordic-clean',
    styleBadge: '🌿 4-Way Stretch Tech-Cotton',
    accentColor: '#2d4a3e',
    description: 'Modern men’s apparel benchmark: 360 stretch fabric matrix, capsule wardrobe builder, anti-odor specs, clean grid, and high-conversion 1-click cart triggers.',
    announcement: 'announcement-clean-v1',
    header: 'hp10-header',
    footer: 'footer-clean-v1',
    sections: [
      'hp10-marquee',
      'hp10-hero',
      'hp10-usp',
      'collection-clean-v1',
      'hp10-bestsellers',
      'hp10-image-with-text',
      'story-clean-v1',
      'hp10-comparison-table',
      'grid-clean-v1',
      'hp10-instagram',
      'hp10-testimonials',
      'hp10-press-logos',
      'trust-badges-v1',
      'banner-clean-v1',
      'hp10-faq',
      'newsletter-clean-v1',
      'hp10-featured-blog',
      'popup-gamified-v1',
      'trust-before-after-clean-v1',
      'gallery-clean-v1',
      'trust-press-quotes-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'beauty-organic-home',
    name: 'Mamaearth / Forest Essentials Clean Ayurveda',
    niche: 'beauty',
    family: 'Organic',
    archetype: 'botanical-glow',
    styleBadge: '🍃 Cold-Pressed Botanical Glow',
    accentColor: '#2e5a44',
    description: 'Clean Ayurvedic beauty benchmark: ingredient sourcing map, dermatologist certifications, toxic-free 10-free guarantee, and before/after clinical results.',
    announcement: 'announcement-clean-v2',
    header: 'hp1-header',
    footer: 'hp1-footer',
    sections: [
      'hp1-marquee',
      'hp1-hero',
      'hp1-usp',
      'collection-clean-v2',
      'hp1-bestsellers',
      'hp1-image-with-text',
      'story-materials-showcase-v1',
      'hp1-comparison-table',
      'grid-clean-v2',
      'hp1-instagram',
      'trust-before-after-clean-v1',
      'hp1-testimonials',
      'hp1-press-logos',
      'trust-certifications-v1',
      'banner-countdown-clean-v1',
      'hp1-faq',
      'newsletter-clean-v2',
      'story-founder-note-v1',
      'popup-spin-wheel-v1',
      'gallery-clean-v2',
      'trust-badges-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'beauty-clinical-home',
    name: 'Minimalist / The Derma Co Clinical Actives',
    niche: 'beauty',
    family: 'Clinical',
    archetype: 'derma-lab',
    styleBadge: '🔬 10% Niacinamide + 2% Salicylic',
    accentColor: '#0284c7',
    description: 'High-efficacy clinical derma benchmark: active percentage matrix, lab trial statistics, skin barrier repair guide, pH balance charts, and chemist formulation specs.',
    announcement: 'announcement-bold-v2',
    header: 'hp14-header',
    footer: 'hp14-footer',
    sections: [
      'hp14-marquee',
      'hp14-hero',
      'hp14-usp',
      'collection-bold-v2',
      'hp14-bestsellers',
      'hp14-image-with-text',
      'hp14-comparison-table',
      'grid-bold-v2',
      'trust-before-after-bold-v1',
      'hp14-instagram',
      'hp14-testimonials',
      'hp14-press-logos',
      'trust-certifications-v1',
      'banner-countdown-bold-v1',
      'hp14-faq',
      'newsletter-bold-v2',
      'story-clean-v2',
      'popup-gamified-v1',
      'trust-press-quotes-v1',
      'gallery-bold-v1',
      'trust-badges-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'beauty-glamour-home',
    name: 'Sugar Cosmetics / Kay Beauty Velvet Glam',
    niche: 'beauty',
    family: 'Glamour',
    archetype: 'glamour-studio',
    styleBadge: '💎 24HR Waterproof Transferproof',
    accentColor: '#e879f9',
    description: 'High-glamour makeup & haute perfumery benchmark: skin tone shade matrix, 24hr wear stress-test, celebrity lookbook, red-carpet reels, and combo creator.',
    announcement: 'announcement-luxury-v2',
    header: 'hp19-header',
    footer: 'hp19-footer',
    sections: [
      'hp19-marquee',
      'hp19-hero',
      'hp19-usp',
      'collection-luxury-v2',
      'hp19-bestsellers',
      'hp19-image-with-text',
      'story-materials-showcase-v1',
      'hp19-comparison-table',
      'grid-luxury-v2',
      'hp19-instagram',
      'trust-before-after-luxury-v1',
      'hp19-testimonials',
      'hp19-press-logos',
      'trust-certifications-v1',
      'banner-countdown-luxury-v1',
      'hp19-faq',
      'newsletter-luxury-v2',
      'gallery-luxury-v2',
      'story-founder-note-v1',
      'popup-spin-wheel-v1',
      'trust-press-quotes-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'jewellery-heritage-home',
    name: 'Tanishq / Amrapali Royal Polki & Gold',
    niche: 'jewellery',
    family: 'Heritage Jewellery',
    archetype: 'royal-polki',
    styleBadge: '👑 BIS 916 Hallmarked Gold',
    accentColor: '#eab308',
    description: 'Imperial Indian fine jewellery benchmark: BIS 916 hallmark laser verifier, uncut Polki setting zoom, bridal necklace layered stack builder, and museum styling.',
    announcement: 'announcement-luxury-v3',
    header: 'hp8-header',
    footer: 'hp8-footer',
    sections: [
      'hp8-marquee',
      'hp8-hero',
      'hp8-usp',
      'collection-luxury-v3',
      'hp8-bestsellers',
      'hp8-image-with-text',
      'story-materials-showcase-v1',
      'hp8-comparison-table',
      'grid-luxury-v3',
      'hp8-instagram',
      'hp8-testimonials',
      'hp8-press-logos',
      'trust-certifications-v1',
      'banner-countdown-luxury-v1',
      'hp8-faq',
      'newsletter-luxury-v3',
      'story-timeline-v1',
      'story-founder-note-v1',
      'popup-exit-intent-luxury-v1',
      'gallery-luxury-v3',
      'trust-press-quotes-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'jewellery-diamond-home',
    name: 'CaratLane / BlueStone Modern Solitaire Diamond',
    niche: 'jewellery',
    family: 'Modern Fine Jewellery',
    archetype: 'modern-solitaire',
    styleBadge: '💎 IGI & GIA Certified 4Cs',
    accentColor: '#0ea5e9',
    description: 'Modern solitaire & lab diamond benchmark: 4Cs interactive clarity scale, platinum alloy durability test, engagement ring customizer, and 360 sparkle visualizer.',
    announcement: 'announcement-clean-v3',
    header: 'hp13-2-header',
    footer: 'hp13-18-footer',
    sections: [
      'hp13-1-announcement-bar',
      'hp13-3-hero',
      'hp13-4-logo-list',
      'hp13-5-rich-text',
      'hp13-6-featured-collection',
      'hp13-7-image-with-text',
      'hp13-8-multicolumn',
      'hp13-9-slideshow',
      'hp13-10-testimonials',
      'hp13-11-instagram-feed',
      'hp13-12-accordion',
      'hp13-13-newsletter',
      'trust-certifications-v1',
      'trust-badges-v1',
      'grid-clean-v3',
      'collection-clean-v3',
      'banner-countdown-clean-v1',
      'story-materials-showcase-v1',
      'popup-gamified-v1',
      'hp13-17-video',
      'trust-press-quotes-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'jewellery-silver-home',
    name: 'GIVA / Shaya Handcrafted 925 Silver',
    niche: 'jewellery',
    family: 'Artisan Silver',
    archetype: 'artisan-silver',
    styleBadge: '🥈 925 Solid Anti-Tarnish Rhodium',
    accentColor: '#78716c',
    description: 'Everyday silver jewellery benchmark: anti-tarnish rhodium seal demo, 3-ring layering trio builder, luxury unboxing gift packaging, and daily wear styling guide.',
    announcement: 'announcement-bold-v3',
    header: 'hp15-2-header',
    footer: 'hp15-18-footer',
    sections: [
      'hp15-1-announcement-bar',
      'hp15-3-hero',
      'hp15-4-logo-list',
      'hp15-5-rich-text',
      'hp15-6-featured-collection',
      'hp15-7-image-with-text',
      'hp15-8-multicolumn',
      'hp15-9-slideshow',
      'hp15-10-testimonials',
      'hp15-11-instagram-feed',
      'hp15-12-accordion',
      'hp15-13-newsletter',
      'trust-certifications-v1',
      'trust-badges-v1',
      'grid-bold-v3',
      'collection-bold-v3',
      'banner-countdown-bold-v1',
      'story-materials-showcase-v1',
      'popup-spin-wheel-v1',
      'hp15-17-video',
      'trust-press-quotes-v1',
      'hp20-18-footer-promo'
    ]
  },
  {
    id: 'tech-audio-home',
    name: 'boAt / Noise Cyber Dark Audio & Electronics',
    niche: 'tech',
    family: 'Cyber Audio',
    archetype: 'cyber-audio',
    styleBadge: '⚡ 60H Playback · 40ms Low Latency',
    accentColor: '#22c55e',
    description: 'High-energy audio & tech wearables benchmark: bass acoustic waveform, 60-hour battery stress graph, IPX7 waterproof splash test, and BEAST low-latency gaming mode switch.',
    announcement: 'announcement-bold-v4',
    header: 'hp20-2-header',
    footer: 'hp20-19-footer',
    sections: [
      'hp20-1-announcement-bar',
      'hp20-3-hero',
      'hp20-4-logo-list',
      'hp20-5-rich-text',
      'hp20-6-featured-collection',
      'hp20-7-image-with-text',
      'hp20-8-multicolumn',
      'hp20-9-slideshow',
      'hp20-10-testimonials',
      'hp20-11-instagram-feed',
      'hp20-12-accordion',
      'hp20-13-newsletter',
      'trust-certifications-v1',
      'trust-badges-v1',
      'grid-bold-v4',
      'collection-bold-v4',
      'banner-countdown-bold-v1',
      'story-materials-showcase-v1',
      'popup-gamified-v1',
      'hp20-17-video',
      'trust-press-quotes-v1',
      'hp20-18-footer-promo'
    ]
  }
];

let allValid = true;
for (const comp of PAGE_COMPOSITIONS_EXPANDED) {
  console.log(`Checking ${comp.name} -> ${comp.sections.length} sections`);
  if (comp.announcement && !regMap.has(comp.announcement)) {
    console.error(`  Missing announcement: ${comp.announcement}`);
    allValid = false;
  }
  if (comp.header && !regMap.has(comp.header)) {
    console.error(`  Missing header: ${comp.header}`);
    allValid = false;
  }
  if (comp.footer && !regMap.has(comp.footer)) {
    console.error(`  Missing footer: ${comp.footer}`);
    allValid = false;
  }
  for (const s of comp.sections) {
    if (!regMap.has(s)) {
      console.error(`  Missing section: ${s}`);
      allValid = false;
    }
  }
}

if (allValid) {
  console.log('🎉 ALL 10 EXPANDED HOMEPAGES & ALL 220+ SECTIONS ARE 100% VALIDATED IN REGISTRY!');
}
